export enum UserRole {
  CLIENT = "CLIENT",
  PHOTOGRAPHER = "PHOTOGRAPHER",
  ADMIN = "ADMIN",
}

export enum BookingStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
}

export enum ReportStatus {
  PENDING = "PENDING",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
}

export enum SystemReportStatus {
  PENDING = "PENDING",
  RESOLVED = "RESOLVED",
}

export enum TestimonialVisibility {
  PUBLIC = "PUBLIC",
  PRIVATE = "PRIVATE",
}

export enum AlbumVisibility {
  PUBLIC = "PUBLIC",
  PRIVATE = "PRIVATE",
}

export enum Suspended {
  SUSPENDED = "SUSPENDED",
  NOT_SUSPENDED = "NOT_SUSPENDED",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  UNPAID = "UNPAID",
}

export enum PaymentType {
  BOOKING = "BOOKING",
  ALBUM_PAYMENT = "ALBUM PAYMENT",
}

export enum PhotographerCategory {
  WEDDING = "WEDDING",
  PORTRAIT = "PORTRAIT",
  LANDSCAPE = "LANDSCAPE",
  EVENT = "EVENT",
  PRODUCT = "PRODUCT",
  FASHION = "FASHION",
  FOOD = "FOOD",
  SPORT = "SPORT",
  ARCHITECTURE = "ARCHITECTURE",
  WILDLIFE = "WILDLIFE",
  TRAVEL = "TRAVEL",
  DOCUMENTARY = "DOCUMENTARY",
  STREET = "STREET",
  FAMILY = "FAMILY",
  NEWBORN = "NEWBORN",
  MATERNITY = "MATERNITY",
  PET = "PET",
  BIRTHDAY = "BIRTHDAY",
  BABY_SHOWER = "BABY_SHOWER",
  ENGAGEMENT = "ENGAGEMENT",
  ANNIVERSARY = "ANNIVERSARY",
  GRADUATION = "GRADUATION",
  PROM = "PROM",
  BACHELOR = "BACHELOR",
  BACHELORETTE = "BACHELORETTE",
  REUNION = "REUNION",
  RETIREMENT = "RETIREMENT",
  FUNERAL = "FUNERAL",
  MEMORIAL = "MEMORIAL",
  RELIGIOUS = "RELIGIOUS",
  CULTURAL = "CULTURAL",
  POLITICAL = "POLITICAL",
  MILITARY = "MILITARY",
  CHARITY = "CHARITY",
  FESTIVAL = "FESTIVAL",
  FAIR = "FAIR",
  CONCERT = "CONCERT",
  CONFERENCE = "CONFERENCE",
  EXPO = "EXPO",
  CONVENTION = "CONVENTION",
  SEMINAR = "SEMINAR",
  WORKSHOP = "WORKSHOP",
  RETREAT = "RETREAT",
  SUMMIT = "SUMMIT",
  TRADE_SHOW = "TRADE_SHOW",
  MEETUP = "MEETUP",
  RALLY = "RALLY",
  PROTEST = "PROTEST",
  MARCH = "MARCH",
  PARADE = "PARADE",
}
